name: Build HTML from Markdown

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to HTML
        run: |
          pandoc basics.md -s -o docs/basics.html --mathjax

      - name: Commit HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/basics.html
          git commit -m "Auto-build HTML from Markdown"
          git push
