name: Build and Deploy MathJax HTML

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir output

          # Главная страница
          pandoc basics.md -s -o output/index.html \
            --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js \
            --metadata title="Круговая математика"

          # Остальные страницы
          pandoc functions.md -s -o output/functions.html \
            --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js \
            --metadata title="Функции"

           # Остальные страницы
          pandoc circular.md -s -o output/circular.html \
            --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js \
            --metadata title="Дуговая алгебра"

            # Остальные страницы
          pandoc calculus.md -s -o output/calculus.html \
            --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js \
            --metadata title="Основы Кругового Математического Анализа"            

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
